
if_gpu: 1
if_amp: 0
data_set_name : "train_corpus_wiki2"
device_id: [6,7]
model_name: "gpt3"
n_attention_layer: 24
rms_norm_eps : 1e-6
n_hidden_size: 512
n_intermediate_size : 512
n_head: 16
n_head_dim: 32
mlp_bias : False
vocab_size: 100276
max_token: 512
max_gen_token: 150
n_batch_size: 32
n_epoch: 10
learning_rate: 0.0005
weight_decay : 0.05
clip_grad_norm : 1.0
if_clip_grad : 1
resid_pdrop: 0.1
attn_pdrop: 0.1
save_per_batchs: 2000
if_train: 1
temperature: 1
top_k: 4  
output_path: "./pt/pt_32l_0_00025_AdamW_wiki2"
pretrain_model : ""
wlist : "./vob/vocab.list.c4.v2"
wlist_size : 100276

